id = "vbnet"
name = "VB.NET"
version = "0.1.9"
schema_version = 1
authors = ["DNA Kode"]
description = "First-class VB.NET language support for Zed"
repository = "https://github.com/DNAKode/vbnet-zed"

[grammars.vbnet]
repository = "https://github.com/DNAKode/tree-sitter-vbnet"
rev = "main"

[language_servers.vbnet-ls]
name = "VB.NET Language Server"
language = "VB.NET"
languages = ["VB.NET"]
language_ids = { "VB.NET" = "vb" }

[debug_adapters.netcoredbg]
schema_path = "debug_adapter_schemas/netcoredbg.json"

[debug_locators.vbnet]
